name: Builder

on:
    push:
      branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: build
              id: build
              run: ./build
            - name: upload
              id: upload
              uses: actions/upload-artifact@v4
              with:
                name: anypy
                path: anypy
                overwrite: true
                compression-level: 0

