name: Release

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        id: build
        run: ./build
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: anypy
